on: [push]

name: CI

jobs:
  build_and_test_ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install alsa
        run: sudo apt-get install -y libasound2-dev
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features